version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres    
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # data
      - ./db/migrations:/docker-entrypoint-initdb.d # migrations
      - ./db/config/postgresql.conf:/etc/postgresql/postgresql.conf # config
      - ./:/var/lib/postgresql/log  # Mount logs to the local machine
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' # Tell Postgres to use the custom config file

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
    restart: always

volumes:
  postgres-data:
