version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres    
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent data volume
      - ./db/migrations:/docker-entrypoint-initdb.d # Initialization scripts (migrations)
      - ./db/config/postgresql.dev.conf:/etc/postgresql/postgresql.conf # Custom configuration
      - ./db/log:/var/log/postgresql # Mount logs
    command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use the custom config file

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
    restart: always

  imgproxy:
    image: darthsim/imgproxy:v3
    container_name: imgproxy
    ports:
      - "8002:8080"
    environment:
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /images
      IMGPROXY_AUTO_WEBP: true
      IMGPROXY_ENABLE_DEBUG_HEADERS: true
      IMGPROXY_ALLOW_UNSAFE_URLS: false
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_SIGNATURE_SIZE: 32
    volumes:
      - ./images:/images:ro

  rembg:
    build: .
    container_name: rembg
    ports:
      - "7001:7000"

volumes:
  postgres-data:
