FROM node:lts-alpine3.22 AS builder

WORKDIR /app

# Copy package files
COPY web/package*.json ./
RUN npm ci

# Copy source code
COPY web/public/ public/
COPY web/src/ src/
COPY web/index.html ./
COPY web/vite.config.ts ./
COPY web/tsconfig.json ./
COPY web/tsconfig.app.json ./
COPY web/tsconfig.node.json ./
# COPY deploy/env/.env.prod .env
COPY deploy/env/.env.prod ./.env.production

# Build application
RUN npm run build

FROM nginx:1.28.0-alpine3.21

# Copy built files
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx configuration
COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]