version: "3.9"
name: marketplace-dev

services:
  nginx:
    container_name: nginx
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.nginx.local
    ports:
      - "8080:80"

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    env_file:
      - ../env/.env.prod        
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent data volume
      - ../../db/migrations:/docker-entrypoint-initdb.d # Initialization scripts (migrations)
      - ../../db/config/postgresql.dev.conf:/etc/postgresql/postgresql.conf # Custom configuration
      - ../../db/log:/var/log/postgresql # Mount logs
    command: postgres -c config_file=/etc/postgresql/postgresql.conf # Use the custom config file 

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8001:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
    restart: always

  imgproxy:
    container_name: imgproxy
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.imgproxy
    ports:
      - "8002:8080"
    env_file:
      - ../env/.env.prod
    volumes:
      - ../../images:/images:ro

  rembg:
    container_name: rembg
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.rembg
    ports:
      - "7001:7000"

volumes:
  postgres-data:
