const { VITE_API_URL, VITE_STRIPE_PUBLISHABLE_KEY, VITE_COUNTRY, PROD, VITE_REQUEST_TIMEOUT } =
  import.meta.env

export const API_URL = PROD ? VITE_API_URL : '/api'
export const STRIPE_PUBLISHABLE_KEY = VITE_STRIPE_PUBLISHABLE_KEY
export const COUNTRY = VITE_COUNTRY
export const REQUEST_TIMEOUT = VITE_REQUEST_TIMEOUT ? parseInt(VITE_REQUEST_TIMEOUT, 10) : 30000
